### ISSUE TITLE
esperanto

### ISSUE THREAD

**Issue by frayoyo** [szabgab/word-games-code#29]
Hello Gabor "SZABGAB" Szabo,
thank you for your patience and help, or better, your guidance for me as a git newbie:
https://codeberg.org/frayoyo/word-games-esperanto
is a new repo with CC_SA-License. Maybe now there is something in it you can use for your word-game.

**Comment by szabgab** [comment]
Thanks, I've added it to the configuration file and now it is available on the site. You can continue updating the categories.json in your repository and it will be reflected on the web site within an hour.
